// AUTO-GENERATED by scripts/pull-catalog-images.mjs
// DO NOT EDIT — re-run the script to update
// Generated: 2026-09-29T15:13:12.926Z
// Source: gs://pos-catalog-images-7ad74935

export const GCS_BASE = 'https://storage.googleapis.com/pos-catalog-images-7ad74935';

/** GCS-hosted product images organized by profile/category/item */
export const CATALOG_IMAGES: Record<string, Record<string, Record<string, string>>> = {
  "kirana": {
    "rice-staples": {
      "sona-masoori-rice": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/sona-masoori-rice.jpg",
      "basmati-rice": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/basmati-rice.jpg",
      "toor-dal": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/toor-dal.jpg",
      "moong-dal": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/moong-dal.jpg",
      "urad-dal": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/urad-dal.jpg",
      "chana-dal": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/rice-staples/chana-dal.jpg"
    },
    "flour-atta": {
      "aashirvaad-atta": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/flour-atta/aashirvaad-atta.jpg",
      "maida-flour": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/flour-atta/maida-flour.jpg",
      "bombay-rava": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/flour-atta/bombay-rava.jpg"
    },
    "sugar-salt": {
      "crystal-sugar": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/sugar-salt/crystal-sugar.jpg",
      "tata-salt": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/sugar-salt/tata-salt.jpg"
    },
    "edible-oils": {
      "sunflower-oil": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/edible-oils/sunflower-oil.jpg",
      "groundnut-oil": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/edible-oils/groundnut-oil.jpg"
    },
    "dairy-ghee": {
      "cow-ghee": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/dairy-ghee/cow-ghee.jpg",
      "toned-milk": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/dairy-ghee/toned-milk.jpg",
      "amul-butter": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/dairy-ghee/amul-butter.jpg",
      "curd-dahi": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/dairy-ghee/curd-dahi.jpg"
    },
    "spices-masala": {
      "turmeric-haldi": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/turmeric-haldi.jpg",
      "red-chilli-powder": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/red-chilli-powder.jpg",
      "coriander-powder": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/coriander-powder.jpg",
      "mustard-seeds": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/mustard-seeds.jpg",
      "jeera-cumin": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/jeera-cumin.jpg",
      "garam-masala": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/spices-masala/garam-masala.jpg"
    },
    "beverages": {
      "red-label-tea": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/beverages/red-label-tea.jpg",
      "bru-instant-coffee": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/beverages/bru-instant-coffee.jpg",
      "bournvita": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/beverages/bournvita.jpg",
      "coca-cola": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/beverages/coca-cola.jpg",
      "sprite": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/beverages/sprite.jpg"
    },
    "snacks-biscuits": {
      "maggi-noodles": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/maggi-noodles.jpg",
      "parle-g-biscuits": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/parle-g-biscuits.jpg",
      "britannia-good-day": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/britannia-good-day.jpg",
      "lays-chips": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/lays-chips.jpg",
      "haldirams-bhujia": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/haldirams-bhujia.jpg",
      "dairy-milk-silk": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/snacks-biscuits/dairy-milk-silk.jpg"
    },
    "personal-home-care": {
      "lifebuoy-soap": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/lifebuoy-soap.jpg",
      "dettol-soap": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/dettol-soap.jpg",
      "colgate-toothpaste": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/colgate-toothpaste.jpg",
      "clinic-plus-shampoo": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/clinic-plus-shampoo.jpg",
      "surf-excel-powder": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/surf-excel-powder.jpg",
      "vim-dishwash": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/vim-dishwash.jpg",
      "harpic-cleaner": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/harpic-cleaner.jpg",
      "goodknight-refill": "https://storage.googleapis.com/pos-catalog-images-7ad74935/kirana/personal-home-care/goodknight-refill.jpg"
    }
  },
  "restaurant": {
    "biryanis-rice": {
      "chicken-dum-biryani": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/chicken-dum-biryani.jpg",
      "mutton-biryani": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/mutton-biryani.jpg",
      "paneer-dum-biryani": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/paneer-dum-biryani.jpg",
      "jeera-rice-dal-tadka": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/jeera-rice-dal-tadka.jpg",
      "veg-biryani": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/veg-biryani.jpg",
      "veg-fried-rice": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/biryanis-rice/veg-fried-rice.jpg"
    },
    "breakfast-tiffins": {
      "masala-dosa": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/masala-dosa.jpg",
      "plain-dosa": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/plain-dosa.jpg",
      "idli-sambar": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/idli-sambar.jpg",
      "medu-vada": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/medu-vada.jpg",
      "poori-bhaji": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/poori-bhaji.jpg",
      "onion-dosa": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/onion-dosa.jpg",
      "bonda": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/bonda.jpg",
      "chapathi": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/chapathi.jpg",
      "upma": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breakfast-tiffins/upma.jpg"
    },
    "curries-gravies": {
      "paneer-butter-masala": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/paneer-butter-masala.jpg",
      "butter-chicken": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/butter-chicken.jpg",
      "chicken-curry": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/chicken-curry.jpg",
      "mutton-curry": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/mutton-curry.jpg",
      "dal-makhani": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/dal-makhani.jpg",
      "dal-tadka": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/dal-tadka.jpg",
      "egg-curry": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/curries-gravies/egg-curry.jpg"
    },
    "starters-appetizers": {
      "chicken-65": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/starters-appetizers/chicken-65.jpg",
      "chilli-paneer": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/starters-appetizers/chilli-paneer.jpg",
      "veg-spring-rolls": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/starters-appetizers/veg-spring-rolls.jpg",
      "samosa": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/starters-appetizers/samosa.jpg"
    },
    "breads-tandoor": {
      "butter-naan": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breads-tandoor/butter-naan.jpg",
      "tandoori-roti": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breads-tandoor/tandoori-roti.jpg",
      "paratha": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/breads-tandoor/paratha.jpg"
    },
    "meals-thali": {
      "veg-meals-unlimited": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/meals-thali/veg-meals-unlimited.jpg",
      "non-veg-meals": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/meals-thali/non-veg-meals.jpg",
      "south-indian-thali": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/meals-thali/south-indian-thali.jpg"
    },
    "beverages-desserts": {
      "filter-coffee": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/filter-coffee.jpg",
      "masala-chai": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/masala-chai.jpg",
      "irani-chai": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/irani-chai.jpg",
      "sweet-lassi": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/sweet-lassi.jpg",
      "fresh-lime-soda": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/fresh-lime-soda.jpg",
      "masala-buttermilk": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/masala-buttermilk.jpg",
      "mineral-water": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/mineral-water.jpg",
      "gulab-jamun-icecream": "https://storage.googleapis.com/pos-catalog-images-7ad74935/restaurant/beverages-desserts/gulab-jamun-icecream.jpg"
    }
  },
  "bakery": {
    "dry-fruit-sweets": {
      "kaju-katli": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/dry-fruit-sweets/kaju-katli.jpg",
      "kaju-pista-roll": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/dry-fruit-sweets/kaju-pista-roll.jpg"
    },
    "ghee-sweets": {
      "mysore-pak": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/ghee-sweets/mysore-pak.jpg",
      "motichoor-laddu": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/ghee-sweets/motichoor-laddu.jpg"
    },
    "syrup-sweets": {
      "gulab-jamun": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/syrup-sweets/gulab-jamun.jpg",
      "rasgulla": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/syrup-sweets/rasgulla.jpg"
    },
    "fresh-breads": {
      "milk-bread": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/fresh-breads/milk-bread.jpg",
      "brown-wheat-bread": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/fresh-breads/brown-wheat-bread.jpg",
      "pav-buns": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/fresh-breads/pav-buns.jpg"
    },
    "pastries-buns": {
      "butter-croissant": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/pastries-buns/butter-croissant.jpg"
    },
    "savouries-puffs": {
      "veg-puff": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/savouries-puffs/veg-puff.jpg",
      "paneer-tikka-puff": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/savouries-puffs/paneer-tikka-puff.jpg",
      "egg-puff": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/savouries-puffs/egg-puff.jpg"
    },
    "cakes-pastries": {
      "black-forest-pastry": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cakes-pastries/black-forest-pastry.jpg",
      "red-velvet-pastry": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cakes-pastries/red-velvet-pastry.jpg",
      "chocolate-cake": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cakes-pastries/chocolate-cake.jpg",
      "pineapple-cake": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cakes-pastries/pineapple-cake.jpg"
    },
    "cookies-biscuits": {
      "osmania-biscuits": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cookies-biscuits/osmania-biscuits.jpg",
      "fruit-biscuits": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/cookies-biscuits/fruit-biscuits.jpg"
    },
    "gift-boxes": {
      "assorted-sweet-box": "https://storage.googleapis.com/pos-catalog-images-7ad74935/bakery/gift-boxes/assorted-sweet-box.jpg"
    }
  },
  "retail": {
    "mens-wear": {
      "polo-tshirt": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/mens-wear/polo-tshirt.jpg",
      "denim-jeans": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/mens-wear/denim-jeans.jpg",
      "formal-shirt": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/mens-wear/formal-shirt.jpg"
    },
    "womens-wear": {
      "cotton-kurti": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/womens-wear/cotton-kurti.jpg",
      "printed-leggings": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/womens-wear/printed-leggings.jpg"
    },
    "kids-wear": {
      "kids-casual-set": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/kids-wear/kids-casual-set.jpg"
    },
    "stationery-books": {
      "classmate-notebook": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/stationery-books/classmate-notebook.jpg",
      "ballpoint-pens": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/stationery-books/ballpoint-pens.jpg",
      "a4-copier-paper": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/stationery-books/a4-copier-paper.jpg"
    },
    "home-kitchen": {
      "storage-basket": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/home-kitchen/storage-basket.jpg",
      "water-bottle-steel": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/home-kitchen/water-bottle-steel.jpg",
      "non-stick-frypan": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/home-kitchen/non-stick-frypan.jpg"
    },
    "electronics-mobiles": {
      "usb-c-cable": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/electronics-mobiles/usb-c-cable.jpg",
      "power-bank": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/electronics-mobiles/power-bank.jpg",
      "bluetooth-earbuds": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/electronics-mobiles/bluetooth-earbuds.jpg"
    },
    "accessories": {
      "leather-wallet": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/accessories/leather-wallet.jpg",
      "travel-backpack": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/accessories/travel-backpack.jpg",
      "duffle-bag": "https://storage.googleapis.com/pos-catalog-images-7ad74935/retail/accessories/duffle-bag.jpg"
    }
  }
};

/** Flat lookup: item slug -> GCS URL */
export const ITEM_IMAGE_MAP: Record<string, string> = {};
for (const categories of Object.values(CATALOG_IMAGES)) {
  for (const items of Object.values(categories)) {
    for (const [slug, url] of Object.entries(items)) {
      ITEM_IMAGE_MAP[slug] = url;
    }
  }
}
