import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Store, ArrowRight, ShieldCheck } from 'lucide-react';
import { AdminApi, ApiError } from './lib/api';
import { StoreWorkspace } from './components/StoreWorkspace';
import { field, primary } from './components/workspace/primitives';
import type { WorkspaceOutlet } from './components/workspace/types';
export const adminApi = new AdminApi();
export function App(){
 const [signedIn,setSignedIn]=useState(adminApi.isAuthenticated);const [outlets,setOutlets]=useState<WorkspaceOutlet[]>([]);const [outletId,setOutletId]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [me,setMe]=useState<{role:string;permissions:string[]}|null>(null);const generation=useRef(0);
 const load=useCallback(async()=>{const version=++generation.current;setLoading(true);setError(null);setMe(null);setOutlets([]);try{const [list,who]=await Promise.all([adminApi.outlets(),adminApi.me()]);if(version!==generation.current)return;if(!Array.isArray(list)||list.some(o=>!o||typeof o.id!=='string'||!o.id||typeof o.name!=='string'))throw new Error('The server returned an invalid outlet list.');if(!who||typeof who.role!=='string'||!Array.isArray(who.permissions)||who.permissions.some((p:unknown)=>typeof p!=='string'))throw new Error('The server did not return valid account permissions. Please retry or sign in again.');setOutlets(list);setOutletId(old=>list.some(o=>o.id===old)?old:list[0]?.id??null);setMe(who);}catch(e){if(version!==generation.current)return;if(e instanceof ApiError&&e.status===401){void adminApi.logout();setSignedIn(false);}else setError((e as Error).message);}finally{if(version===generation.current)setLoading(false);}},[]);
 useEffect(()=>{if(signedIn)void load();return()=>{++generation.current;};},[signedIn,load]);
 const outlet=useMemo(()=>outlets.find(o=>o.id===outletId)??null,[outlets,outletId]);
 if(!signedIn)return <SignIn onSignedIn={()=>{setLoading(true);setSignedIn(true);setError(null);}}/>;
 return <StoreWorkspace api={adminApi} outlets={outlets} outlet={outlet} onOutlet={setOutletId} identity={me} loading={loading} error={error} onRetry={()=>void load()} onLogout={()=>{++generation.current;void adminApi.logout();setMe(null);setOutlets([]);setOutletId(null);setSignedIn(false);}}/>;
}
function SignIn({onSignedIn}:{onSignedIn:()=>void}){
 const [slug,setSlug]=useState('');const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <div className="store-workspace"><main className="flex min-h-screen items-center justify-center bg-slate-50 px-6 py-20"><div className="grid w-full max-w-4xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl md:grid-cols-2"><section className="hidden flex-col justify-between bg-gradient-to-br from-orange-500 via-orange-600 to-amber-700 p-10 text-white md:flex"><div className="text-xl font-extrabold tracking-tight">NovaPOS / Backoffice</div><div><Store size={38} className="mb-5 text-amber-200"/><h1 className="text-3xl font-extrabold leading-tight tracking-tight">German Precision.<br/>Effortless Service.</h1><p className="mt-4 text-sm leading-relaxed text-orange-100">Live Zomato-style KOT dispatch, smart billing, and real-time operations, unified in one powerful workspace.</p></div><p className="flex items-center gap-2 text-xs text-orange-200"><ShieldCheck size={16}/>Bank-Grade Secure Multi-Tenant Architecture</p></section><form className="space-y-5 p-7 md:p-10" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await adminApi.login(slug.trim(),identifier.trim(),password);onSignedIn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div><p className="text-[10px] font-bold uppercase tracking-widest text-orange-600">ENTERPRISE STORE WORKSPACE</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-900">Welcome Back</h2><p className="mt-2 text-sm text-slate-500">Sign in to access your live store operations.</p></div><label className="block text-xs font-semibold text-slate-600">Store / Business Slug<input className={`${field} mt-2`} required value={slug} onChange={e=>setSlug(e.target.value)} placeholder="your-store" autoComplete="organization"/></label><label className="block text-xs font-semibold text-slate-600">Mobile or username<input className={`${field} mt-2`} required value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" placeholder="Your registered phone or email"/></label><label className="block text-xs font-semibold text-slate-600">PIN / Password<input className={`${field} mt-2`} required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={busy} className={`${primary} w-full py-3 text-sm font-bold shadow-md shadow-orange-500/25`}>{busy?'Signing in…':'Open Live Operations'}<ArrowRight size={16}/></button></form></div></main></div>;
}
