import { TaxCalculator } from './workspace/TaxCalculator';
import { useEffect, useState } from 'react';
import { LayoutDashboard, UtensilsCrossed, Printer, ChartNoAxesCombined, LogOut, Store, ShieldCheck, ArrowUpRight, Zap, Flame } from 'lucide-react';
import type { AdminApi } from '../lib/api';
import { button, card, ErrorState, EmptyState, Skeleton, SlideOver, WorkspaceBoundary } from './workspace/primitives';
import { WorkspaceHeader } from './workspace/WorkspaceHeader';
import { OperationsHub } from './workspace/OperationsHub';
import { LiveOpsDashboard } from './workspace/LiveOpsDashboard';
import { CatalogWorkspace } from './workspace/CatalogWorkspace';
import { HardwareWorkspace, ReportsWorkspace } from './workspace/HardwareReports';
import { WebPosPunchModal } from './workspace/WebPosPunchModal';
import { type DateRange, type WorkspaceOutlet, presetRange } from './workspace/types';
import '../styles/workspace.css';
export interface StoreWorkspaceProps {api:AdminApi;outlets:WorkspaceOutlet[];outlet:WorkspaceOutlet|null;onOutlet:(id:string)=>void;identity:{role:string;permissions:string[]}|null;loading:boolean;error:string|null;onRetry:()=>void;onLogout:()=>void;}
const nav=[{key:'live-ops',path:'/store/live-ops',label:'Live Orders & KDS',section:'OPERATIONS',icon:Flame,permission:'menu:read'},{key:'dashboard',path:'/store/dashboard',label:'Analytics & Sales',icon:LayoutDashboard,permission:'report:read'},{key:'catalog',path:'/store/catalog',label:'Menu & Catalog',icon:UtensilsCrossed,permission:'menu:read'},{key:'reports',path:'/store/reports',label:'Sales Reports',section:'FINANCE & SETUP',icon:ChartNoAxesCombined,permission:'report:read'},{key:'hardware',path:'/store/hardware',label:'Thermal Printing',icon:Printer,permission:'settings:read'} ,{key:'tax',path:'/store/tax',label:'GST Tax Rules',icon:ShieldCheck,permission:'settings:read'}] as const;
/** The store page the URL points at; anything outside /store/* falls back to Live Orders. Keeps refresh and Back/Forward on the right screen. */
export function resolveStorePath(pathname: string = typeof location === 'undefined' ? '' : location.pathname): string {
  return pathname.startsWith('/store/') ? pathname : '/store/live-ops';
}

export function StoreWorkspace({api,outlets,outlet,onOutlet,identity,loading,error,onRetry,onLogout}:StoreWorkspaceProps){
 const [path,setPath]=useState(resolveStorePath);const [mobile,setMobile]=useState(false);const [range,setRange]=useState<DateRange>(()=>presetRange('Today',outlet?.timezone));const [quick,setQuick]=useState<'order'|'cash'|'profile'|null>(null);
 useEffect(()=>{const update=()=>setPath(resolveStorePath());window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);
 useEffect(()=>{setRange(presetRange('Today',outlet?.timezone));},[outlet?.id]);
 const allowed=identity?nav.filter(n=>identity.permissions.includes(n.permission)):[];const current=allowed.find(n=>n.path===path)??allowed[0];
 const navigate=(url:string)=>{history.pushState(null,'',url);setPath(url);setMobile(false);};
 return <div className="store-workspace"><div className="min-h-screen bg-slate-50 font-sans text-slate-800"><div className="flex min-h-screen"><aside data-no-print className={`${mobile?'flex':'hidden'} fixed inset-y-0 left-0 z-40 w-[232px] shrink-0 flex-col border-r border-slate-200 bg-white p-4 shadow-xl lg:sticky lg:top-0 lg:flex lg:h-screen lg:shadow-none`}><a href="/store/live-ops" onClick={e=>{e.preventDefault();navigate('/store/live-ops');}} className="flex items-center gap-2.5 px-3 py-5 no-underline"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-orange-500 to-amber-600 text-white shadow-md shadow-orange-500/25"><Flame size={20} className="text-white" /></div><div className="flex flex-col"><span className="text-base font-extrabold tracking-tight text-slate-900 leading-none">NovaPOS</span><span className="text-[9px] font-bold tracking-wider text-orange-600 uppercase mt-0.5">Live Store Station</span></div></a><div className="mb-5 mt-2 flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3"><Store size={17} className="shrink-0 text-orange-600"/><div className="min-w-0"><p className="truncate text-xs font-semibold">{outlet?.name||'Store workspace'}</p><p className="mt-0.5 text-[10px] text-slate-500 font-mono">{outlet?.code ? `OUTLET · ${outlet.code}` : (loading ? 'Loading…' : 'READY')}</p></div></div><nav aria-label="Store navigation" className="flex-1 space-y-1">{(identity?allowed:nav).map(n=><div key={n.key}>{'section' in n&&<p className="px-3 pb-2 pt-5 text-[9px] font-bold tracking-[.14em] text-slate-400">{n.section}</p>}<button disabled={!identity||loading} aria-current={current?.key===n.key?'page':undefined} onClick={()=>navigate(n.path)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-[13px] font-medium transition-colors ${current?.key===n.key?'bg-orange-50 text-orange-700 font-semibold border-l-2 border-orange-500':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><n.icon size={17}/>{n.label}{current?.key===n.key&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-orange-600"/>}</button></div>)}</nav><div className="mt-8 rounded-xl bg-orange-50/50 border border-orange-100 p-4"><ShieldCheck size={18} className="mb-2 text-orange-600"/><p className="text-xs font-semibold text-slate-900">German Industrial Core</p><p className="mt-1 text-[11px] leading-relaxed text-slate-500">Live KOT sync & fiscal compliance active.</p></div><button className="mt-4 flex items-center gap-3 rounded-lg px-3 py-3 text-left text-xs text-slate-500 hover:bg-slate-50" onClick={onLogout}><LogOut size={16}/>Sign out</button>{mobile&&<button className={`${button} lg:hidden`} onClick={()=>setMobile(false)}>Close navigation</button>}</aside>{mobile&&<button data-no-print aria-label="Close navigation overlay" className="fixed inset-0 z-30 bg-slate-900/40 lg:hidden" onClick={()=>setMobile(false)}/>}
 <div className="min-w-0 flex-1"><WorkspaceHeader outlet={outlet} outlets={outlets} onOutlet={onOutlet} range={range} onRange={setRange} role={identity?.role??'Checking access…'} onMenu={()=>setMobile(v=>!v)} onQuickAction={setQuick}/><main className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8 lg:py-8" aria-busy={loading}>{loading?<Skeleton/>:error?<ErrorState error={error} retry={onRetry} label="Retry"/>:!allowed.length?<EmptyState title="No admin access" detail="Your account has no permissions for these pages. Ask your administrator to update your access." action={<button className={button} onClick={onRetry}>Retry</button>}/>:!outlet?<EmptyState title="No outlets assigned" detail="Ask your administrator to assign an active outlet, then retry." action={<button className={button} onClick={onRetry}>Retry</button>}/>:<WorkspaceBoundary key={`${outlet.id}:${current?.key}`}><div key={`${outlet.id}:${current?.key}`}>
 {current?.key==='live-ops'&&<LiveOpsDashboard api={api} outlet={outlet} onOpenPunchModal={()=>setQuick('order')}/>}{current?.key==='tax'&&<TaxCalculator outlet={outlet}/>}{current?.key==='dashboard'&&<OperationsHub api={api} outlet={outlet} range={range}/>}{current?.key==='catalog'&&<CatalogWorkspace api={api} outlet={outlet} canWrite={identity?.permissions.includes('menu:write')??false}/>}{current?.key==='hardware'&&<HardwareWorkspace api={api} outlet={outlet}/>}{current?.key==='reports'&&<ReportsWorkspace api={api} outlet={outlet} range={range}/>}
 </div></WorkspaceBoundary>}</main><footer data-no-print className="flex flex-wrap items-center justify-between gap-2 px-8 pb-6 text-[10px] text-slate-400"><span>NovaPOS · Enterprise Store Operations</span><span>Secure workspace / {identity?.role??'Access verification'}</span></footer></div></div>
 {quick==='order'&&outlet&&<WebPosPunchModal api={api} outlet={outlet} onClose={()=>setQuick(null)} onOrderPlaced={()=>{onRetry();}}/>}
 {quick&&quick!=='order'&&<SlideOver title={quick==='profile'?'Your workspace':'Cash drawer status'} onClose={()=>setQuick(null)}>{quick==='profile'?<div className="space-y-4"><div className={`${card} p-4`}><p className="text-sm font-bold">{outlet?.name||'No outlet selected'}</p><p className="mt-2 text-sm text-slate-500">Role: {identity?.role??'Unverified'}</p></div><button className={button} onClick={onLogout}><LogOut size={15}/>Sign out</button></div>:<EmptyState title="Drawer telemetry unavailable" detail="Cash collections are available in Sales Reports. Physical drawer open/closed status is not supplied by the server." action={allowed.some(n=>n.key==='reports')?<button className={button} onClick={()=>{navigate('/store/reports');setQuick(null);}}>View collections <ArrowUpRight size={14}/></button>:undefined}/>}</SlideOver>}
 </div></div>;
}
