import { TaxCalculator } from './workspace/TaxCalculator';
import { useEffect, useState } from 'react';
import { LayoutDashboard, UtensilsCrossed, Printer, ChartNoAxesCombined, LogOut, Store, ShieldCheck, ArrowUpRight, BookOpen } from 'lucide-react';
import type { AdminApi } from '../lib/api';
import { button, card, ErrorState, EmptyState, Skeleton, SlideOver, WorkspaceBoundary } from './workspace/primitives';
import { WorkspaceHeader } from './workspace/WorkspaceHeader';
import { OperationsHub } from './workspace/OperationsHub';
import { CatalogWorkspace } from './workspace/CatalogWorkspace';
import { HardwareWorkspace, ReportsWorkspace } from './workspace/HardwareReports';
import { type DateRange, type WorkspaceOutlet, presetRange } from './workspace/types';
import '../styles/workspace.css';
export interface StoreWorkspaceProps {api:AdminApi;outlets:WorkspaceOutlet[];outlet:WorkspaceOutlet|null;onOutlet:(id:string)=>void;identity:{role:string;permissions:string[]}|null;loading:boolean;error:string|null;onRetry:()=>void;onLogout:()=>void;}
const nav=[{key:'dashboard',path:'/store/dashboard',label:'Dashboard',section:'OPERATIONS',icon:LayoutDashboard,permission:'report:read'},{key:'catalog',path:'/store/catalog',label:'Menu & Catalog',icon:UtensilsCrossed,permission:'menu:read'},{key:'reports',path:'/store/reports',label:'Sales Reports',section:'FINANCE & SETUP',icon:ChartNoAxesCombined,permission:'report:read'},{key:'hardware',path:'/store/hardware',label:'Thermal Printing',icon:Printer,permission:'settings:read'} ,{key:'tax',path:'/store/tax',label:'GST Tax Rules',icon:ShieldCheck,permission:'settings:read'}] as const;
export function StoreWorkspace({api,outlets,outlet,onOutlet,identity,loading,error,onRetry,onLogout}:StoreWorkspaceProps){
 const [path,setPath]=useState(location.pathname);const [mobile,setMobile]=useState(false);const [range,setRange]=useState<DateRange>(()=>presetRange('Today',outlet?.timezone));const [quick,setQuick]=useState<'order'|'cash'|'profile'|null>(null);
 useEffect(()=>{const update=()=>setPath(location.pathname);window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);
 useEffect(()=>{setRange(presetRange('Today',outlet?.timezone));},[outlet?.id]);
 const allowed=identity?nav.filter(n=>identity.permissions.includes(n.permission)):[];const current=allowed.find(n=>n.path===path)??allowed[0];
 const navigate=(url:string)=>{history.pushState(null,'',url);setPath(url);setMobile(false);};
 return <div className="store-workspace"><div className="min-h-screen bg-slate-50 font-sans text-slate-800"><div className="flex min-h-screen"><aside data-no-print className={`${mobile?'flex':'hidden'} fixed inset-y-0 left-0 z-40 w-[232px] shrink-0 flex-col border-r border-slate-200 bg-white p-4 shadow-xl lg:sticky lg:top-0 lg:flex lg:h-screen lg:shadow-none`}><a href="/store/dashboard" onClick={e=>{e.preventDefault();navigate('/store/dashboard');}} className="flex items-center gap-2 px-3 py-5 text-xl font-black tracking-tight text-slate-900 no-underline"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-forest text-base text-white">N</span>NovaPOS<span className="ml-1 rounded border border-slate-200 px-1 text-[9px] font-semibold text-slate-400">BACKOFFICE</span></a><div className="mb-5 mt-3 flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3"><Store size={17} className="shrink-0 text-slate-400"/><div className="min-w-0"><p className="truncate text-xs font-semibold">{outlet?.name||'Store workspace'}</p><p className="mt-1 text-[10px] text-slate-400">{outlet?.code||'VERIFYING ACCESS'}</p></div></div><nav aria-label="Store navigation" className="flex-1 space-y-1">{(identity?allowed:nav).map(n=><div key={n.key}>{'section' in n&&<p className="px-3 pb-2 pt-5 text-[9px] font-bold tracking-[.14em] text-slate-400">{n.section}</p>}<button disabled={!identity||loading} aria-current={current?.key===n.key?'page':undefined} onClick={()=>navigate(n.path)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-[13px] font-medium transition-colors ${current?.key===n.key?'bg-emerald-50 text-forest':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><n.icon size={17}/>{n.label}{current?.key===n.key&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-emerald-600"/>}</button></div>)}</nav><div className="mt-8 rounded-xl bg-slate-50 p-4"><ShieldCheck size={18} className="mb-2 text-emerald-700"/><p className="text-xs font-semibold">Your store. Your workspace.</p><p className="mt-1 text-[11px] leading-relaxed text-slate-400">Access is verified for your role and assigned outlets.</p></div><button className="mt-4 flex items-center gap-3 rounded-lg px-3 py-3 text-left text-xs text-slate-500 hover:bg-slate-50" onClick={onLogout}><LogOut size={16}/>Sign out</button>{mobile&&<button className={`${button} lg:hidden`} onClick={()=>setMobile(false)}>Close navigation</button>}</aside>{mobile&&<button data-no-print aria-label="Close navigation overlay" className="fixed inset-0 z-30 bg-slate-900/40 lg:hidden" onClick={()=>setMobile(false)}/>}
 <div className="min-w-0 flex-1"><WorkspaceHeader outlet={outlet} outlets={outlets} onOutlet={onOutlet} range={range} onRange={setRange} role={identity?.role??'Checking access…'} onMenu={()=>setMobile(v=>!v)} onQuickAction={setQuick}/><main className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8 lg:py-8" aria-busy={loading}>{loading?<Skeleton/>:error?<ErrorState error={error} retry={onRetry} label="Retry"/>:!allowed.length?<EmptyState title="No admin access" detail="Your account has no permissions for these pages. Ask your administrator to update your access." action={<button className={button} onClick={onRetry}>Retry</button>}/>:!outlet?<EmptyState title="No outlets assigned" detail="Ask your administrator to assign an active outlet, then retry." action={<button className={button} onClick={onRetry}>Retry</button>}/>:<WorkspaceBoundary key={`${outlet.id}:${current?.key}`}><div key={`${outlet.id}:${current?.key}`}>
 {current?.key==='tax'&&<TaxCalculator outlet={outlet}/>} {current?.key==='dashboard'&&<OperationsHub api={api} outlet={outlet} range={range}/>}{current?.key==='catalog'&&<CatalogWorkspace api={api} outlet={outlet} canWrite={identity?.permissions.includes('menu:write')??false}/>}{current?.key==='hardware'&&<HardwareWorkspace api={api} outlet={outlet}/>}{current?.key==='reports'&&<ReportsWorkspace api={api} outlet={outlet} range={range}/>}
 </div></WorkspaceBoundary>}</main><footer data-no-print className="flex flex-wrap items-center justify-between gap-2 px-8 pb-6 text-[10px] text-slate-400"><span>NovaPOS · Store operations</span><span>Secure workspace / {identity?.role??'Access verification'}</span></footer></div></div>
 {quick&&<SlideOver title={quick==='profile'?'Your workspace':quick==='cash'?'Cash drawer status':'Punch a new order'} onClose={()=>setQuick(null)}>{quick==='profile'?<div className="space-y-4"><div className={`${card} p-4`}><p className="text-sm font-bold">{outlet?.name||'No outlet selected'}</p><p className="mt-2 text-sm text-slate-500">Role: {identity?.role??'Unverified'}</p></div><button className={button} onClick={onLogout}><LogOut size={15}/>Sign out</button></div>:<EmptyState title={quick==='cash'?'Drawer telemetry unavailable':'Continue on your POS terminal'} detail={quick==='cash'?'Cash collections are available in Sales Reports. Physical drawer open/closed status is not supplied by the server.':'Use the connected NovaPOS terminal to create and settle orders. This backoffice does not currently expose an order-entry endpoint.'} action={quick==='cash'&&allowed.some(n=>n.key==='reports')?<button className={button} onClick={()=>{navigate('/store/reports');setQuick(null);}}>View collections <ArrowUpRight size={14}/></button>:undefined}/>}</SlideOver>}
 </div></div>;
}
