import { useEffect, useRef, useState } from 'react';
import { Check, Download, LayoutGrid, List, Pencil, Search, Package, SlidersHorizontal } from 'lucide-react';
import { type AdminApi, downloadCsv } from '../../lib/api';
import { button, primary, card, field, SlideOver, EmptyState, ErrorState, Skeleton, useResource } from './primitives';
import { type Category, type MenuItem, type WorkspaceOutlet, money } from './types';
export interface ItemEditorProps {item:MenuItem;onClose:()=>void;onSave:(updates:Pick<MenuItem,'name'|'priceMinor'|'taxSlabId'|'hsnSac'>)=>Promise<void>}
export function ItemEditor({item,onClose,onSave}:ItemEditorProps){
 const [name,setName]=useState(item.name);const [price,setPrice]=useState((item.priceMinor/100).toFixed(2));const [tax,setTax]=useState(item.taxSlabId);const [hsn,setHsn]=useState(item.hsnSac??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <SlideOver title="Edit menu item" subtitle={item.code||'Catalog item'} onClose={onClose} busy={busy}><form className="space-y-5" onSubmit={async e=>{e.preventDefault();if(busy)return;const amount=Number(price);if(!name.trim()||!/^\d+(\.\d{1,2})?$/.test(price)||!Number.isFinite(amount)||amount<0||amount>21474836){setError('Enter an item name and a valid price with up to two decimal places.');return;}setBusy(true);setError('');try{await onSave({name:name.trim(),priceMinor:Math.round(amount*100),taxSlabId:tax,hsnSac:hsn.trim()});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label className="block text-xs font-semibold text-slate-600">Item name<input required maxLength={150} className={`${field} mt-2`} value={name} onChange={e=>setName(e.target.value)}/></label><div className="grid grid-cols-2 gap-4"><label className="block text-xs font-semibold text-slate-600">Base price (₹)<input inputMode="decimal" required className={`${field} mt-2 font-mono`} value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="block text-xs font-semibold text-slate-600">GST slab<select className={`${field} mt-2`} value={tax} onChange={e=>setTax(e.target.value)}>{!['gst-0','gst-5','gst-12','gst-18','gst-28'].includes(tax)&&<option value={tax}>{tax}</option>}{[0,5,12,18,28].map(n=><option key={n} value={`gst-${n}`}>{n}% GST</option>)}</select></label></div><label className="block text-xs font-semibold text-slate-600">HSN / SAC code<input className={`${field} mt-2 font-mono`} maxLength={12} value={hsn} onChange={e=>setHsn(e.target.value)}/></label>
 <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="flex items-center gap-2 text-sm font-bold text-slate-700"><Package size={16}/>Packaging charge</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">Not configurable through the current catalog API. No packaging fee will be added by this editor.</p></section><section className="rounded-xl border border-slate-200 p-4"><h3 className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal size={16}/>Modifier groups</h3><p className="mt-2 text-xs leading-relaxed text-slate-500">Modifier editing is not connected. Existing choices such as extra cheese or spice level are preserved.</p></section><p className="text-xs leading-relaxed text-slate-500">Updates apply to new orders. Issued invoices keep their original price and tax snapshots.</p>{error&&<div role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="flex justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" className={button} onClick={onClose} disabled={busy}>Cancel</button><button className={primary} disabled={busy}><Check size={16}/>{busy?'Saving…':'Save changes'}</button></div></form></SlideOver>;
}
export function CatalogWorkspace({api,outlet,canWrite}:{api:AdminApi;outlet:WorkspaceOutlet;canWrite:boolean}){
 const resource=useResource(async()=>{const [items,categories]=await Promise.all([api.items(),api.categories()]);if(!Array.isArray(items)||!Array.isArray(categories))throw new Error('Catalog response is incomplete.');return {items:items as MenuItem[],categories:categories as Category[]};},[outlet.id]);
 const [items,setItems]=useState<MenuItem[]>([]);useEffect(()=>{if(resource.data)setItems(resource.data.items);},[resource.data]);
 const [category,setCategory]=useState('');const [search,setSearch]=useState('');const [grid,setGrid]=useState(false);const [editing,setEditing]=useState<MenuItem|null>(null);const [error,setError]=useState('');const [saving,setSaving]=useState<string[]>([]);const locks=useRef(new Set<string>());
 const toggle=async(item:MenuItem)=>{if(!canWrite||locks.current.has(item.id))return;locks.current.add(item.id);setSaving([...locks.current]);setError('');setItems(rows=>rows.map(r=>r.id===item.id?{...r,isActive:!item.isActive}:r));try{await api.updateItem(item.id,{isActive:!item.isActive});}catch(e){setItems(rows=>rows.map(r=>r.id===item.id?{...r,isActive:item.isActive}:r));setError(`Availability was not saved: ${(e as Error).message}`);}finally{locks.current.delete(item.id);setSaving([...locks.current]);}};
 if(resource.error)return <ErrorState error={resource.error} retry={resource.retry}/>;if(!resource.data)return <Skeleton/>;
 const categories=resource.data.categories;const visible=items.filter(i=>(!category||i.categoryId===category)&&[i.name,i.code].some(v=>v?.toLowerCase().includes(search.toLowerCase())));const fmt=(n:number)=>money(n,outlet.currency??'INR');
 const availability=(item:MenuItem)=><button role="switch" aria-label={`Availability for ${item.name}`} aria-checked={item.isActive} disabled={!canWrite||saving.includes(item.id)} onClick={()=>void toggle(item)} className={`relative inline-flex h-7 w-12 shrink-0 items-center rounded-full p-1 transition-colors ${item.isActive?'bg-emerald-600':'bg-slate-300'}`}><span className={`h-5 w-5 rounded-full bg-white shadow transition-transform ${item.isActive?'translate-x-5':'translate-x-0'}`}/></button>;
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-1 text-[10px] font-bold uppercase tracking-[.18em] text-emerald-700">Operations / Catalog</p><h1 className="text-2xl font-bold tracking-tight">Menu & Catalog</h1><p className="mt-2 text-sm text-slate-500">Keep every item ready for your next order.</p></div><button className={button} disabled={!items.length} onClick={()=>downloadCsv('catalog',items.map(i=>({name:i.name,code:i.code??'',price:(i.priceMinor/100).toFixed(2),tax:i.taxSlabId,available:i.isActive})))}><Download size={15}/>Export catalog</button></div>{error&&<div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="grid gap-5 lg:grid-cols-[210px_minmax(0,1fr)]"><aside className={`${card} self-start p-3`}><h2 className="px-3 py-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Categories</h2>{[{id:'',name:'All items'},...categories].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)} className={`mb-1 flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-sm ${category===c.id?'bg-emerald-50 font-semibold text-forest':'text-slate-600 hover:bg-slate-50'}`}><span>{c.name}</span><span className="rounded bg-white px-1.5 font-mono text-xs text-slate-400">{c.id?items.filter(i=>i.categoryId===c.id).length:items.length}</span></button>)}</aside><section className={`${card} min-w-0`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div className="relative min-w-[180px] flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className={`${field} pl-9`} aria-label="Search catalog" placeholder="Search by name or item code" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="flex gap-1"><button className={button} aria-label="Table view" aria-pressed={!grid} onClick={()=>setGrid(false)}><List size={17}/></button><button className={button} aria-label="Grid view" aria-pressed={grid} onClick={()=>setGrid(true)}><LayoutGrid size={17}/></button></div></div>
 {!visible.length?<EmptyState title="No items found" detail="Choose another category or clear your search."/>:grid?<div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map(i=><article key={i.id} className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex h-20 items-center justify-center rounded-lg bg-slate-50 text-slate-300"><UtensilTile name={i.name}/></div><h3 className="truncate text-sm font-bold">{i.name}</h3><p className="mt-1 font-mono text-lg font-bold text-forest">{fmt(i.priceMinor)}</p><div className="mt-4 flex items-center justify-between">{availability(i)}<button disabled={!canWrite||saving.includes(i.id)} className={button} onClick={()=>setEditing(i)}><Pencil size={14}/>Edit</button></div></article>)}</div>:<div className="overflow-x-auto"><table><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{['Item details','Category','Price','GST','Available',''].map((v,k)=><th className="px-4 py-3 font-semibold" key={k}>{v}</th>)}</tr></thead><tbody>{visible.map(i=><tr key={i.id} className="border-b border-slate-100 hover:bg-slate-50/70"><td className="px-4 py-4"><div className="flex items-center gap-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${i.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-400'}`}><Package size={15}/></span><div><strong className="text-sm font-semibold">{i.name}</strong><p className="mt-1 font-mono text-[11px] text-slate-400">{i.code||'No code'}</p></div></div></td><td className="px-4 py-4 text-xs text-slate-500">{categories.find(c=>c.id===i.categoryId)?.name??'—'}</td><td className="whitespace-nowrap px-4 py-4 font-mono text-sm font-semibold">{fmt(i.priceMinor)}</td><td className="px-4 py-4 text-xs text-slate-500">{i.taxSlabId}</td><td className="px-4 py-4">{availability(i)}</td><td className="px-4 py-4"><button className={button} disabled={!canWrite||saving.includes(i.id)} aria-label={`Edit ${i.name}`} onClick={()=>setEditing(i)}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>}<footer className="border-t border-slate-100 p-4 text-xs text-slate-500">{visible.length} items · Availability is saved to the server. Terminals receive it on their next catalog sync.</footer></section></div>
 {editing&&<ItemEditor item={editing} onClose={()=>setEditing(null)} onSave={async updates=>{await api.updateItem(editing.id,updates);setItems(rows=>rows.map(i=>i.id===editing.id?{...i,...updates}:i));}}/>}</div>;
}
function UtensilTile({name}:{name:string}){return <span className="text-3xl font-bold tracking-tight">{name.trim().slice(0,2).toUpperCase()}</span>;}
