import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, ArrowUpRight as ExternalArrow, Banknote, ChartNoAxesCombined, ChefHat, Download, ReceiptText, RefreshCw, ShoppingBag, UtensilsCrossed } from 'lucide-react';
import { type AdminApi, downloadCsv } from '../../lib/api';
import { button, card, EmptyState, ErrorState, Skeleton, useResource } from './primitives';
import { type DateRange, type SaleDay, type WorkspaceOutlet, money, rangeBounds, shiftDay } from './types';
const sum=(rows:SaleDay[],key:keyof SaleDay)=>rows.reduce((s,r)=>s+Number(r[key]??0),0);
function Sparkline({values}:{values:number[]}){if(values.length<2)return <span className="text-[10px] text-slate-400">Trend needs 2+ days</span>;const max=Math.max(1,...values),min=Math.min(0,...values);return <svg viewBox="0 0 120 32" className="h-8 w-28" role="img" aria-label="Daily sales trend"><polyline points={values.map((v,i)=>`${i/(values.length-1)*120},${30-(v-min)/(max-min)*26}`).join(' ')} fill="none" stroke="#059669" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
export function OperationsHub({api,outlet,range}:{api:AdminApi;outlet:WorkspaceOutlet;range:DateRange}){
 const [tick,setTick]=useState(0);useEffect(()=>{const t=setInterval(()=>{if(document.visibilityState==='visible')setTick(v=>v+1);},30000);return()=>clearInterval(t);},[]);
 const resource=useResource(async()=>{const bounds=rangeBounds(range,outlet.timezone);const previous=rangeBounds({preset:'Yesterday',from:shiftDay(range.from,-1),to:shiftDay(range.from,-1)},outlet.timezone);const [today,days,yesterday]=await Promise.all([api.today(outlet.id),api.sales(outlet.id,bounds.from,bounds.to),api.sales(outlet.id,previous.from,previous.to)]);if(!Array.isArray(days)||!Array.isArray(yesterday))throw new Error('Sales response was incomplete. Retry reports.');return{today,days:days as SaleDay[],yesterday:yesterday as SaleDay[],updated:new Date()};},[outlet.id,range.from,range.to,tick]);
 if(resource.error)return <ErrorState error={resource.error} retry={resource.retry} label="Retry reports"/>;if(!resource.data)return <Skeleton/>;
 const {today,days,yesterday}=resource.data;const gross=sum(days,'grossMinor'),net=sum(days,'netMinor'),orders=sum(days,'orders'),previousNet=sum(yesterday,'netMinor');const delta=previousNet?((net-previousNet)/previousNet*100):null;const fmt=(n:number)=>money(n,outlet.currency??'INR');const peak=Math.max(1,...days.map(d=>d.grossMinor));
 const metrics=[{label:'Net sales',value:fmt(net),icon:Banknote,hint:'After tax · paid orders'},{label:'Total orders',value:String(orders),icon:ShoppingBag,hint:'Across all sales channels'},{label:'Average order value',value:fmt(orders?Math.round(gross/orders):0),icon:ReceiptText,hint:'Gross sales / paid orders'},{label:'Tax collected',value:fmt(sum(days,'taxMinor')),icon:ChartNoAxesCombined,hint:'Frozen invoice snapshots'}];
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-1 text-[10px] font-bold uppercase tracking-[.18em] text-emerald-700">Operations / Overview</div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Your business, at a glance.</h1><p className="mt-2 text-sm text-slate-500">A clear view of sales, service and the shift ahead.</p></div><button className={button} onClick={resource.retry}><RefreshCw size={14}/>Refresh</button></div>
 <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((m,i)=><article key={m.label} className={`${card} min-h-[158px] p-5 transition-shadow hover:shadow-md`}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{m.label}</span><m.icon size={16} className="text-emerald-700"/></div><div className="mt-4 font-mono text-2xl font-bold tracking-tight text-slate-900">{m.value}</div><div className="mt-3 flex min-h-[32px] items-center justify-between gap-2"><span className="text-[11px] text-slate-500">{i===0&&range.preset==='Today'&&delta!==null?<span className={`inline-flex items-center gap-1 ${delta>=0?'text-emerald-700':'text-rose-600'}`}>{delta>=0?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {Math.abs(delta).toFixed(1)}% vs yesterday</span>:m.hint}</span>{i===0&&<Sparkline values={days.map(d=>d.netMinor)}/>}</div></article>)}</div>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_310px]"><section className={card}><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">Sales performance</h2><p className="mt-1 text-xs text-slate-500">Gross revenue by business day</p></div><button className={button} disabled={!days.length} onClick={()=>downloadCsv(`sales-${outlet.code}-${range.from}`,days.map(d=>({...d})))}><Download size={14}/>Export</button></div>{days.length?<div className="p-5"><div className="flex items-end gap-2"><strong className="font-mono text-2xl font-bold">{fmt(gross)}</strong><span className="pb-1 text-xs text-slate-400">gross revenue</span></div><div className="mt-6 flex h-[205px] items-end gap-2 overflow-x-auto border-b border-slate-200">{days.map(d=><div key={d.day} className="flex h-full min-w-[30px] flex-1 flex-col justify-end gap-2"><div title={`${d.day}: ${fmt(d.grossMinor)} · ${d.orders} orders`} className="w-full rounded-t-md bg-emerald-600/80 transition-colors hover:bg-emerald-800" style={{height:`${Math.max(0,d.grossMinor/peak*170)}px`}}/><span className="pb-2 text-center font-mono text-[10px] text-slate-400">{d.day.slice(5)}</span></div>)}</div></div>:<EmptyState title="Your first sale starts the story" detail="Paid orders will appear here. Try a different date range to review previous sales."/>}<footer className="border-t border-slate-100 px-5 py-3 text-[11px] text-slate-400">Last received {resource.data.updated.toLocaleTimeString()} · refreshes every 30 seconds</footer></section>
 <section className={`${card} p-5`}><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Live service</h2><span className="rounded-md border border-emerald-200 bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">CURRENT</span></div><div className="mt-5 flex items-center justify-between border-b border-slate-100 pb-5"><span className="flex items-center gap-3 text-sm text-slate-500"><UtensilsCrossed size={18}/>Open tabs</span><strong className="font-mono text-xl">{today.openOrders??'—'}</strong></div><div className="mt-5 flex items-center justify-between border-b border-slate-100 pb-5"><span className="flex items-center gap-3 text-sm text-slate-500"><ChefHat size={18}/>Kitchen tickets</span><strong className="font-mono text-xl">{today.pendingKots??'—'}</strong></div><div className="mt-5 rounded-lg bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-700">Table occupancy</p><p className="mt-2 text-xs leading-relaxed text-slate-500">Table capacity is not available in this report. Open tabs are not an occupancy percentage.</p></div></section></div>
 <div className="grid gap-5 lg:grid-cols-2"><section className={card}><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-bold">Hourly sales & footfall</h2><p className="mt-1 text-xs text-slate-500">Lunch and dinner demand</p></div><EmptyState title="Hourly data isn’t connected yet" detail="The current report contains daily totals. Hourly revenue and guest counts will appear when supplied by the reporting service."/></section><section className={card}><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-bold">Category & channel mix</h2><p className="mt-1 text-xs text-slate-500">Dine-in · Takeaway · Delivery</p></div><EmptyState title="Channel breakdown unavailable" detail="Category rankings and order-channel totals require the corresponding server report. All-channel sales above remain accurate."/></section></div></div>;
}
