import { Component, type ErrorInfo, type ReactNode, useEffect, useRef, useState } from 'react';
import { AlertTriangle, RefreshCw, SearchX, X } from 'lucide-react';
export const button = 'inline-flex min-h-[40px] items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 disabled:opacity-50';
export const primary = 'inline-flex min-h-[40px] items-center justify-center gap-2 rounded-lg bg-forest px-4 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-emerald-800 disabled:opacity-50';
export const field = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800';
export const card = 'rounded-xl border border-slate-200/80 bg-white shadow-sm';
export function EmptyState({title,detail,action}:{title:string;detail:string;action?:ReactNode}) {return <div className="flex min-h-[230px] flex-col items-center justify-center gap-3 p-8 text-center"><div className="rounded-2xl bg-slate-100 p-4 text-slate-400"><SearchX size={28}/></div><h3 className="text-base font-semibold text-slate-800">{title}</h3><p className="max-w-md text-sm leading-relaxed text-slate-500">{detail}</p>{action}</div>;}
export function ErrorState({error,retry,busy=false,label='Retry Connection'}:{error:unknown;retry:()=>void;busy?:boolean;label?:string}) {const message=error instanceof Error?error.message:String(error);const local=['localhost','127.0.0.1'].includes(location.hostname);return <section role="alert" className={`${card} flex min-h-[230px] flex-col items-center justify-center gap-3 border-rose-200 p-8 text-center`}><div className="rounded-2xl bg-rose-50 p-4 text-rose-600"><AlertTriangle size={26}/></div><h2 className="text-lg font-semibold text-slate-800">We couldn’t load this workspace</h2><p className="max-w-lg text-sm text-slate-600">{message}</p><p className="max-w-md text-xs leading-relaxed text-slate-500">{local?'Check your local API terminal and the connection to port 3001.':'Check your internet connection. The service may need a moment to wake up.'}</p><button className={primary} disabled={busy} onClick={retry}><RefreshCw size={15} className={busy?'animate-spin':''}/>{label}</button></section>;}
export function Skeleton(){return <div role="status" aria-label="Loading workspace" className="grid min-h-[350px] grid-cols-2 gap-4 lg:grid-cols-4">{[0,1,2,3].map(i=><div key={i} className={`${card} h-36 animate-pulse p-5`}><div className="h-3 w-24 rounded bg-slate-100"/><div className="mt-6 h-8 w-32 rounded bg-slate-100"/></div>)}<div className={`${card} col-span-full h-56 animate-pulse bg-slate-100`}/></div>;}
export class WorkspaceBoundary extends Component<{children:ReactNode},{error:Error|null}> {state={error:null as Error|null};static getDerivedStateFromError(error:Error){return{error};}componentDidCatch(_error:Error,_info:ErrorInfo){}render(){return this.state.error?<ErrorState error={this.state.error} retry={()=>this.setState({error:null})}/>:this.props.children;}}
export function SlideOver({title,subtitle,children,onClose,busy=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;busy?:boolean}) {
 const panel=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){e.preventDefault();close.current();}if(e.key==='Tab'){const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')??[]);if(!nodes.length){e.preventDefault();return;}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===panel.current)){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[busy]);
 return <div className="fixed inset-0 z-[90] flex justify-end bg-slate-950/40 backdrop-blur-sm" onClick={()=>{if(!busy)onClose();}}><div ref={panel} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} onClick={e=>e.stopPropagation()} className="flex h-full w-full max-w-lg flex-col bg-white shadow-2xl"><header className="flex shrink-0 items-center justify-between border-b border-slate-200 p-6"><div><h2 className="text-xl font-bold tracking-tight">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div><button aria-label="Close drawer" disabled={busy} className={button} onClick={onClose}><X size={18}/></button></header><div className="flex-1 overflow-y-auto p-6">{children}</div></div></div>;
}
export function useResource<T>(load:()=>Promise<T>,keys:unknown[]) {
 const [state,setState]=useState<{data:T|null;error:Error|null;loading:boolean}>({data:null,error:null,loading:true});const [version,reload]=useState(0);
 useEffect(()=>{let active=true;setState({data:null,error:null,loading:true});load().then(data=>{if(active)setState({data,error:null,loading:false});}).catch(error=>{if(active)setState({data:null,error:error instanceof Error?error:new Error(String(error)),loading:false});});return()=>{active=false;};},[...keys,version]);
 return {...state,retry:()=>reload(v=>v+1)};
}
