import { useMemo, useState } from 'react';
import { computeTax, findRuleSet } from '@novapos/tax-engine';
import { card, field } from './primitives';
import type { WorkspaceOutlet } from './types';
export function TaxCalculator({outlet}:{outlet:WorkspaceOutlet}){
 const india=outlet.country==='IN';const [amount,setAmount]=useState('118.00');const [slab,setSlab]=useState(india?'gst-18':'vat-standard');const [interstate,setInterstate]=useState(false);
 const result=useMemo(()=>{try{if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('Enter a non-negative amount with up to two decimal places.');const rule=findRuleSet(india?'IN-GST':'EU-VAT-DE');if(!rule)throw new Error('No rule set available.');const value=computeTax(rule,[{lineId:'preview',amountMinor:Math.round(Number(amount)*100),slabId:slab}],{outletCountry:outlet.country,outletRegion:'KA',placeOfSupplyRegion:interstate?'MH':'KA'});return {value,error:''};}catch(e){return{value:null,error:(e as Error).message};}},[amount,slab,interstate,india,outlet.country]);
 return <div className="space-y-5"><div><h1 className="text-2xl font-bold tracking-tight">GST Tax Rules</h1><p className="mt-2 text-sm text-slate-500">Preview tax with the same engine used by the POS. This does not change your store’s tax configuration.</p></div><section className={`${card} max-w-3xl p-6`}><h2 className="mb-5 text-sm font-bold">Tax calculation preview</h2><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-500">Amount<input className={`${field} mt-2 font-mono`} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-xs font-semibold text-slate-500">Tax slab<select className={`${field} mt-2`} value={slab} onChange={e=>setSlab(e.target.value)}>{(india?['gst-0','gst-5','gst-12','gst-18','gst-28']:['vat-zero','vat-reduced','vat-standard']).map(v=><option key={v}>{v}</option>)}</select></label>{india&&<label className="text-xs font-semibold text-slate-500">Place of supply<select className={`${field} mt-2`} value={String(interstate)} onChange={e=>setInterstate(e.target.value==='true')}><option value="false">Same state</option><option value="true">Another state</option></select></label>}</div>{result.error?<p role="alert" className="mt-5 rounded-lg bg-rose-50 p-4 text-sm text-rose-700">{result.error}</p>:<div className="mt-5 rounded-lg bg-emerald-50 p-5 font-mono text-sm leading-loose text-forest"><p>Taxable: {(result.value!.taxableMinor/100).toFixed(2)}</p>{result.value!.componentTotals.map(c=><p key={c.code}>{c.code} {(c.rate*100).toFixed(2)}%: {(c.amountMinor/100).toFixed(2)}</p>)}<strong>Total: {(result.value!.totalMinor/100).toFixed(2)}</strong></div>}</section></div>;
}
